name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**' #test skip Ci
jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: run tests
        run : npm run test
