name: demo workflow
on: push
jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "hi"
      - name: multi line
        run: |
          echo "multi line "
          echo "simple print"
